# Modified from https://levelup.gitconnected.com/dockerizing-a-flask-application-with-a-postgres-database-b5e5bfc24848
version: "3.9"
services:
  web:
    depends_on:
      - db
    environment:
      STAGE: ${STAGE}
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
      FLASK_SECRET: ${FLASK_SECRET}
    image: lactantius/makeheadlines:0.3
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./server:/usr/src/app/server
    restart: always

  db:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    image: postgres:alpine
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
